// <auto-generated />
using System;
using Lynkr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lynkr.Migrations
{
    [DbContext(typeof(LynkrDBContext))]
    [Migration("20251124012927_AddIdentityAndSeedData")]
    partial class AddIdentityAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lynkr.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Lynkr.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionUserId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 21, 1, 29, 26, 892, DateTimeKind.Unspecified).AddTicks(5143), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "ACCEPTED",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 11, 21, 1, 29, 26, 892, DateTimeKind.Unspecified).AddTicks(5292), new TimeSpan(0, 0, 0, 0, 0)),
                            User1Id = 1,
                            User2Id = 2
                        },
                        new
                        {
                            Id = 2,
                            ActionUserId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 24, 0, 29, 26, 892, DateTimeKind.Unspecified).AddTicks(5678), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = "PENDING",
                            User1Id = 2,
                            User2Id = 3
                        });
                });

            modelBuilder.Entity("Lynkr.Models.Like", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Lynkr.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Lynkr.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "First post from Alice!",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 19, 1, 29, 26, 892, DateTimeKind.Unspecified).AddTicks(4023), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://placehold.co/600x400/4CAF50/white?text=Alice+Post",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bob checking in with a new post.",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 22, 1, 29, 26, 892, DateTimeKind.Unspecified).AddTicks(4412), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageUrl = "https://placehold.co/600x400/2196F3/white?text=Bob+Post",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Lynkr.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c26d504f-d046-42b2-8cf9-e9342a181720",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 14, 1, 29, 26, 759, DateTimeKind.Unspecified).AddTicks(2430), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "alice@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice Admin",
                            NormalizedEmail = "ALICE@TEST.COM",
                            NormalizedUserName = "ALICE@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEMGXvBf4iZJWSduXdYtglIHF+knyOhbj21m/VcyIUM2jWzG1covyMnHwPMWXJ78ww==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://placehold.co/100x100/4CAF50/white?text=A",
                            SecurityStamp = "da3089f9-8fa8-42f0-b457-1389196f7a83",
                            TwoFactorEnabled = false,
                            UserName = "alice@test.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca71dcd6-3b6e-45e9-9846-812a6f9a70f5",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 19, 1, 29, 26, 805, DateTimeKind.Unspecified).AddTicks(3285), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "bob@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob Beta",
                            NormalizedEmail = "BOB@TEST.COM",
                            NormalizedUserName = "BOB@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPsfLg67AwkS3HcQhLlsiymzzKBfKyHgAVASpF30xUJe+URckWwr446K0KfzntwNUA==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://placehold.co/100x100/2196F3/white?text=B",
                            SecurityStamp = "baabe55c-1d4b-4905-80a2-48aadd4a75c3",
                            TwoFactorEnabled = false,
                            UserName = "bob@test.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f311642-bc43-4cfe-9ae8-da6d2833b5f6",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 22, 1, 29, 26, 849, DateTimeKind.Unspecified).AddTicks(216), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "charlie@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Charlie Chat",
                            NormalizedEmail = "CHARLIE@TEST.COM",
                            NormalizedUserName = "CHARLIE@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEqTog4WoAjBPuSeVHkFIkEkn9DG3A7KyXPb06tZI7qhhcOzPdyGs3MGE0pKKxKqNQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://placehold.co/100x100/FF9800/white?text=C",
                            SecurityStamp = "da23659c-6134-4107-8e9e-e2e1367fbe2c",
                            TwoFactorEnabled = false,
                            UserName = "charlie@test.com"
                        });
                });

            modelBuilder.Entity("Lynkr.Models.Conversation", b =>
                {
                    b.HasOne("Lynkr.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lynkr.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Lynkr.Models.Friendship", b =>
                {
                    b.HasOne("Lynkr.Models.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lynkr.Models.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Lynkr.Models.Like", b =>
                {
                    b.HasOne("Lynkr.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynkr.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lynkr.Models.Message", b =>
                {
                    b.HasOne("Lynkr.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynkr.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Lynkr.Models.Post", b =>
                {
                    b.HasOne("Lynkr.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lynkr.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lynkr.Models.Post", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Lynkr.Models.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
